name: chat_application
description: Chat application using firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.5
  get: ^4.6.5
  shared_preferences: ^2.2.0
  package_info: ^2.0.2
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  # http
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  crypto: ^3.0.3
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  fluttertoast: ^8.2.2
  dots_indicator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  #example
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400

    - family: Montserrat
      fonts:
       - asset: assets/fonts/Montserrat-Medium.ttf
         weight: 500
       - asset: assets/fonts/Montserrat-SemiBold.ttf
         weight: 600

    - family: Iconfont
      fonts:
       - asset: assets/fonts/iconfont.ttf
         weight: 400


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
